# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: xenial
os:
  - linux
julia:
  - 1.2
  - 1.3
addons:
  apt:
    packages:
      - python3-pip
      - python3-venv
env:
  global:
    # Suppress "Could not connect to display" warnings from GR Framework.
    # * https://gr-framework.org/about.html#file-formats
    # * https://github.com/jheinen/gr/blob/v0.31.1/lib/gks/util.c#L67
    - GKS_WSTYPE: png
  #   - JULIA_DEBUG=Main,Base
matrix:
  fast_finish: true
notifications:
  email: false

before_script:
  - unset JULIA_PROJECT
  - julia --color=yes -e '
    using Pkg;
    pkg"add PackageCompiler#54c0c1255227c8a94de402b41e05d22ea98b5013"
    '

  # See: https://github.com/JuliaPy/Pandas.jl/blob/v1.3.0/.travis.yml
  - pip3 install --user --upgrade pip
  - pip --version
  - pip install --user pandas
  - pip install --user tables

script:
  - make
  - make test

after_script:
  - make dump-setup
