# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: xenial
os:
  - linux
julia:
  - 1.1
addons:
  apt:
    packages:
      - python3-pip
      - python3-venv
env:
  # global:
  #   - JULIA_DEBUG=Main,Base
  matrix:
    - TARGET=diffeq GROUP=Interface
    - TARGET=diffeq GROUP=Integrators
    - TARGET=diffeq GROUP=Regression
    - TARGET=diffeq GROUP=AlgConvergence_I
    - TARGET=diffeq GROUP=AlgConvergence_II
    - TARGET=diffeq GROUP=AlgConvergence_III
    # - TARGET=makie
matrix:
  fast_finish: true
notifications:
  email: false

before_script:
  - julia --color=yes -e '
    using Pkg;
    Pkg.add("PackageCompiler")
    '

script:
  - make -C $TARGET
  - make -C $TARGET test

after_script:
  - make -C $TARGET dump-setup
