# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false

before_script:
  - julia --color=yes -e '
    using Pkg;
    Pkg.add("PackageCompiler")
    '

script:
  - make -C python
  - make -C plots
