# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: xenial
os:
  - linux
julia:
  - 1.1
  - nightly
addons:
  apt:
    packages:
      - python3-pip
      - python3-venv
env:
  - TARGET=python
  - TARGET=plots
  - TARGET=all
  - TARGET=rebugger
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false

before_script:
  - julia --color=yes -e '
    using Pkg;
    Pkg.add("PackageCompiler")
    '

script:
  - make -C $TARGET
  - make -C $TARGET test

after_script:
  - make -C $TARGET dump-setup
